input_power_dbm = -30.0
frequency_hz = 1.0e9

[[blocks]]
type = "explicit"
name = "Low Noise Amplifier"
gain_db = 30.0
noise_figure_db = 3.0
output_p1db_dbm = 5.0

[[blocks]]
type = "explicit"
name = "Attenuator"
gain_db = -6.0
noise_figure_db = 6.0

[[blocks]]
type = "explicit"
name = "High Power Amplifier"
gain_db = 30.0
noise_figure_db = 3.0
output_p1db_dbm = 20.0
