input_power_dbm = -120.0
frequency_hz = 6.0e9

[[blocks]]
type = "explicit"
name = "Low Noise Amplifier"
gain_db = 10.0
noise_figure_db = 6.0

[[blocks]]
type = "explicit"
name = "Mixer"
gain_db = -5.0
noise_figure_db = 6.0

[[blocks]]
type = "explicit"
name = "IF Amplifier"
gain_db = 15.0
noise_figure_db = 8.0
